name: Deploy Frontend to GHCR
on:
  push:
    branches:
      - main
      
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create .env.production
        run: echo "${{ secrets.FRONTEND_ENV }}" > .env.production

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ranandasatria/myapp:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 9301
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/ranandasatria/myapp:latest
            docker rm -f myapp || true
            docker run -d -p 9302:80 --name myapp ghcr.io/ranandasatria/myapp:latest